name: Deploy to Cloud Functions

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: suribase  # SUBSTITUA
  FUNCTION_NAME: jira-queue-api  # SUBSTITUA (nome da sua Cloud Function)
  REGION: us-central1  # SUBSTITUA
  SERVICE_ACCOUNT_EMAIL: suri-certificates-management@suribase.iam.gserviceaccount.com # SUBSTITUA

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/87769041781/locations/global/workloadIdentityPools/suri-github-actions-pool/providers/github-actions-provider' # SUBSTITUA
        service_account: ${{ env.SERVICE_ACCOUNT_EMAIL }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2'
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy to Cloud Functions
      run: |
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --gen2 \
          --runtime=python39 \
          --region=${{ env.REGION }} \
          --source=. \
          --entry-point=salvar_e_enviar \
          --trigger-http \
          --allow-unauthenticated \
          --service-account=${{ env.SERVICE_ACCOUNT_EMAIL }} \
          --set-secrets="JIRA_TASK_API_URL=jira-management:latest,BUCKET_NAME=bucket-name:latest" \
          --project=${{ env.PROJECT_ID }}